### ISSUE TITLE
try to use webrtc throw exception 

### ISSUE THREAD

**Issue by clarkshu1016** [rfazi/android_webrtc#1]
FATAL EXCEPTION: main
                                                                                                    Process: it.rfazi.webrtcexample, PID: 22547
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjingle_peerconnection_so.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:20)
                                                                                                    	at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:41)
                                                                                                    	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:296)
                                                                                                    	at it.rfazi.webrtcexample.MainActivity.initWebRTC(MainActivity.kt:49)
                                                                                                    	at it.rfazi.webrtcexample.MainActivity.onCreate(MainActivity.kt:31)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by rfazi** [comment]
Have you included 'libs' folder in the project?

**Comment by abdul02123** [comment]
Yes, I  have included 'libs' folder in the project but still throwing error:
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjingle_peerconnection_so.so" not found
